/**
 * Copyright (c) 2026 Apurva Nakade. All rights reserved.
 * Released under Apache 2.0 license as described in the file LICENSE.
 * Authors: Apurva Nakade
 */

// Concatenates src/js/** and src/css/** in src/manifest.mjs order into the
// local Quarto extension at _extensions/mathviz-local/dist/, the same way
// mathviz's scripts/build.mjs builds its own bundle. The extension's filter
// (mathviz-local.lua) adds both files to every page after mathviz's, so the
// functions here extend the VM that mathviz already defined.
//
// The output is committed, like mathviz's dist/: `quarto render` runs no
// npm step. Run `node _mathviz/scripts/build.mjs` after editing anything
// under _mathviz/src/.

import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { js, css } from '../src/manifest.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.resolve(root, '../_extensions/mathviz-local/dist')
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')

const license = (open, close) => [
  `${open}`,
  ` * Copyright (c) 2026 Apurva Nakade. All rights reserved.`,
  ` * Released under Apache 2.0 license as described in the file LICENSE.`,
  ` * Authors: Apurva Nakade`,
  ` ${close}`,
  ``
].join('\n')

// Each source file is an IIFE ending in `})(window)` with no semicolon; the
// lone `;` between files keeps two of them from parsing as one call (see
// the comment on `bundle` in mathviz's scripts/build.mjs).
function bundle(files, srcDir, comment, separator) {
  let out = ''
  for (const rel of files) {
    out += `\n${comment(`---- ${srcDir}/${rel} ----`)}\n${separator}`
    out += read(path.join(srcDir, rel))
    if (!out.endsWith('\n')) out += '\n'
  }
  return out
}

const banner = 'mathviz-local -- generated by _mathviz/scripts/build.mjs from _mathviz/src/manifest.mjs; do not edit, edit _mathviz/src/ and rebuild.'

const jsOut = license('/**', '*/') + `// ${banner}\n` + bundle(js, 'src/js', (t) => `// ${t}`, ';\n')
const cssOut = license('/*', '*/') + `/* ${banner} */\n` + bundle(css, 'src/css', (t) => `/* ${t} */`, '')

fs.mkdirSync(outDir, { recursive: true })
fs.writeFileSync(path.join(outDir, 'mathviz-local.js'), jsOut)
fs.writeFileSync(path.join(outDir, 'mathviz-local.css'), cssOut)
execFileSync(process.execPath, ['--check', path.join(outDir, 'mathviz-local.js')], { stdio: 'inherit' })

console.log(`mathviz-local: ${js.length} js + ${css.length} css files -> ${path.relative(process.cwd(), outDir)}`)
