/**
 * Copyright (c) 2026 Apurva Nakade. All rights reserved.
 * Released under Apache 2.0 license as described in the file LICENSE.
 * Authors: Apurva Nakade
 */

// Concatenates src/js/** and src/css/** -- in the order src/manifest.mjs
// lists them, which is the order the browser must run them in -- into
// dist/mathviz.js and dist/mathviz.css, then copies both into the Quarto
// extension folder. No minifier, no bundler, no dependencies: the output is
// the readable source with file separators, so a stack trace in a consumer's
// browser still points at a recognizable file.
//
// dist/ is committed on purpose. `quarto add apurvanakade/mathviz` pulls a
// plain archive of this repository and runs nothing, and jsDelivr serves
// files straight from a tag -- both need the built files to be in git. CI
// fails if a commit changes src/ without rebuilding (see
// .github/workflows/ci.yml), so the two cannot drift.

import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { js, css } from '../src/manifest.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')

// The version is written in three places a consumer can see (the npm
// manifest, the extension manifest Quarto reads, and the Lua filter that
// names the site_libs folder). Refuse to build unless they agree.
const pkgVersion = JSON.parse(read('package.json')).version
const extVersion = read('_extensions/mathviz/_extension.yml').match(/^version:\s*["']?([^"'\s]+)/m)?.[1]
const luaVersion = read('_extensions/mathviz/mathviz.lua').match(/^local VERSION\s*=\s*"([^"]+)"/m)?.[1]
if (pkgVersion !== extVersion || pkgVersion !== luaVersion) {
  console.error(`Version mismatch: package.json=${pkgVersion} _extension.yml=${extVersion} mathviz.lua=${luaVersion}`)
  process.exit(1)
}

const license = (open, close) => [
  `${open}`,
  ` * Copyright (c) 2026 Apurva Nakade. All rights reserved.`,
  ` * Released under Apache 2.0 license as described in the file LICENSE.`,
  ` * Authors: Apurva Nakade`,
  ` ${close}`,
  ``
].join('\n')

// `separator` is emitted between files. For JS it is a lone semicolon: each
// source file is an IIFE that ends in a call -- `})(window)`, or `})()` for
// a module that exports nothing -- with no trailing semicolon, and two of
// those back to back parse as `})(window)(function ...)` -- the first
// file's return value called with the second file as its argument.
// That is syntactically valid, so `node --check` below can't catch it; the
// page just died with "(intermediate value)(...) is not a function" after
// the first file. The semicolon makes each file its own statement.
function bundle(files, srcDir, comment, separator) {
  let out = ''
  for (const rel of files) {
    out += `\n${comment(`---- ${srcDir}/${rel} ----`)}\n${separator}`
    out += read(path.join(srcDir, rel))
    if (!out.endsWith('\n')) out += '\n'
  }
  return out
}

const banner = `mathviz v${pkgVersion} -- generated by scripts/build.mjs from src/manifest.mjs; do not edit, edit src/ and rebuild.`

const jsOut = license('/**', '*/') + `// ${banner}\n` + bundle(js, 'src/js', (t) => `// ${t}`, ';\n')
const cssOut = license('/*', '*/') + `/* ${banner} */\n` + bundle(css, 'src/css', (t) => `/* ${t} */`, '')

fs.mkdirSync(path.join(root, 'dist'), { recursive: true })
fs.writeFileSync(path.join(root, 'dist/mathviz.js'), jsOut)
fs.writeFileSync(path.join(root, 'dist/mathviz.css'), cssOut)

// A concatenation can be syntactically valid file-by-file and still break as
// one script (a file missing its trailing semicolon before an IIFE, say).
execFileSync(process.execPath, ['--check', path.join(root, 'dist/mathviz.js')], { stdio: 'inherit' })

const extDist = path.join(root, '_extensions/mathviz/dist')
fs.mkdirSync(extDist, { recursive: true })
for (const name of ['mathviz.js', 'mathviz.css']) {
  fs.copyFileSync(path.join(root, 'dist', name), path.join(extDist, name))
}

// starter/ is a complete Quarto site a newcomer copies and runs; it needs
// the extension installed, which is exactly `_extensions/mathviz/` copied
// in (what `quarto add apurvanakade/mathviz` does). Mirror it here so the
// starter is committed in a working state and tracks the working tree
// rather than a published tag. Remove first so a file deleted from the
// extension doesn't linger in the copy. CI diffs this too.
const starterExt = path.join(root, 'starter/_extensions/mathviz')
fs.rmSync(starterExt, { recursive: true, force: true })
fs.cpSync(path.join(root, '_extensions/mathviz'), starterExt, { recursive: true })

const kb = (rel) => (fs.statSync(path.join(root, rel)).size / 1024).toFixed(0)
console.log(`dist/mathviz.js  ${kb('dist/mathviz.js')} kB (${js.length} files)`)
console.log(`dist/mathviz.css ${kb('dist/mathviz.css')} kB (${css.length} files)`)
