/**
 * Copyright (c) 2026 Apurva Nakade. All rights reserved.
 * Released under Apache 2.0 license as described in the file LICENSE.
 * Authors: Apurva Nakade
 */

// Concatenates src/js/** and src/css/** -- in the order src/manifest.mjs
// lists them, which is the order the browser must run them in -- into
// dist/mathviz.js and dist/mathviz.css, then copies both into the Quarto
// extension folder. No minifier, no bundler, no dependencies: the output is
// the readable source with file separators, so a stack trace in a consumer's
// browser still points at a recognizable file.
//
// dist/ is committed on purpose. `quarto add apurvanakade/mathviz` pulls a
// plain archive of this repository and runs nothing, and jsDelivr serves
// files straight from a tag -- both need the built files to be in git. CI
// fails if a commit changes src/ without rebuilding (see
// .github/workflows/ci.yml), so the two cannot drift.

import fs from 'node:fs'
import path from 'node:path'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { js, css } from '../src/manifest.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')

// The version is written in three places a consumer can see (the npm
// manifest, the extension manifest Quarto reads, and the Lua filter that
// names the site_libs folder). Refuse to build unless they agree.
const pkgVersion = JSON.parse(read('package.json')).version
const extVersion = read('_extensions/mathviz/_extension.yml').match(/^version:\s*["']?([^"'\s]+)/m)?.[1]
const luaVersion = read('_extensions/mathviz/mathviz.lua').match(/^local VERSION\s*=\s*"([^"]+)"/m)?.[1]
if (pkgVersion !== extVersion || pkgVersion !== luaVersion) {
  console.error(`Version mismatch: package.json=${pkgVersion} _extension.yml=${extVersion} mathviz.lua=${luaVersion}`)
  process.exit(1)
}

const license = (open, close) => [
  `${open}`,
  ` * Copyright (c) 2026 Apurva Nakade. All rights reserved.`,
  ` * Released under Apache 2.0 license as described in the file LICENSE.`,
  ` * Authors: Apurva Nakade`,
  ` ${close}`,
  ``
].join('\n')

// `separator` is emitted between files. For JS it is a lone semicolon: each
// source file is an IIFE that ends in a call -- `})(window)`, or `})()` for
// a module that exports nothing -- with no trailing semicolon, and two of
// those back to back parse as `})(window)(function ...)` -- the first
// file's return value called with the second file as its argument.
// That is syntactically valid, so `node --check` below can't catch it; the
// page just died with "(intermediate value)(...) is not a function" after
// the first file. The semicolon makes each file its own statement.
function bundle(files, srcDir, comment, separator) {
  let out = ''
  for (const rel of files) {
    out += `\n${comment(`---- ${srcDir}/${rel} ----`)}\n${separator}`
    out += read(path.join(srcDir, rel))
    if (!out.endsWith('\n')) out += '\n'
  }
  return out
}

const banner = `mathviz v${pkgVersion} -- generated by scripts/build.mjs from src/manifest.mjs; do not edit, edit src/ and rebuild.`

const jsOut = license('/**', '*/') + `// ${banner}\n` + bundle(js, 'src/js', (t) => `// ${t}`, ';\n')
const cssOut = license('/*', '*/') + `/* ${banner} */\n` + bundle(css, 'src/css', (t) => `/* ${t} */`, '')

fs.mkdirSync(path.join(root, 'dist'), { recursive: true })
fs.writeFileSync(path.join(root, 'dist/mathviz.js'), jsOut)
fs.writeFileSync(path.join(root, 'dist/mathviz.css'), cssOut)

// A concatenation can be syntactically valid file-by-file and still break as
// one script (a file missing its trailing semicolon before an IIFE, say).
execFileSync(process.execPath, ['--check', path.join(root, 'dist/mathviz.js')], { stdio: 'inherit' })

// The optional Quarto theme: src/theme/theme.scss filled in once per color
// scheme with the chrome tokens' values from tokens.css (see the template's
// header comment for how a site opts in). Generated rather than authored
// twice so the Bootstrap chrome it colors can never disagree with the
// --vm-* defaults the panels read.
const themeTokens = [
  'bg', 'surface', 'surface-hover', 'text', 'text-soft', 'border', 'accent',
  'accent-hover', 'on-accent', 'grid', 'radius', 'radius-sm', 'shadow'
]

// Reads `--vm-<name>: <value>;` declarations out of the tokens.css block
// whose selector starts with `selectorStart`. One declaration per line is
// the file's own format; a value spanning lines would come back missing and
// fail the check in theme() rather than be silently cut short.
function tokenBlock(tokensCss, selectorStart) {
  const start = tokensCss.indexOf(selectorStart)
  if (start === -1) throw new Error(`tokens.css has no block starting ${selectorStart}`)
  const body = tokensCss.slice(tokensCss.indexOf('{', start) + 1, tokensCss.indexOf('\n}', start))
  const values = {}
  for (const m of body.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/--vm-([\w-]+):\s*([^;\n]+);/g)) {
    values[m[1]] = m[2].trim()
  }
  return values
}

const tokensCss = read('src/css/tokens.css')
const lightTokens = tokenBlock(tokensCss, ':where(:root)')
// The dark block only redeclares what changes; radius and the like carry over.
const darkTokens = { ...lightTokens, ...tokenBlock(tokensCss, ':where(body.quarto-dark') }
const themeTemplate = read('src/theme/theme.scss')

function theme(scheme, values, selector) {
  let tokens = ''
  let properties = ''
  for (const name of themeTokens) {
    if (values[name] === undefined) throw new Error(`tokens.css declares no --vm-${name} for the ${scheme} theme`)
    tokens += `$vm-${name}: ${values[name]} !default;\n`
    properties += `  --vm-${name}: #{$vm-${name}};\n`
  }
  // The template's own license header stays; the banner goes right under it.
  const out = themeTemplate
    .replace('*/\n', `*/\n\n// ${banner} (${scheme} scheme)\n`)
    .replace('{{tokens}}\n', tokens)
    .replace('{{selector}}', selector)
    .replace('{{properties}}\n', properties)
  if (out.includes('{{tokens}}') || out.includes('{{selector}}') || out.includes('{{properties}}')) {
    throw new Error('src/theme/theme.scss: a marker was left unfilled')
  }
  return out
}

fs.mkdirSync(path.join(root, 'dist/theme'), { recursive: true })
fs.writeFileSync(path.join(root, 'dist/theme/mathviz-light.scss'), theme('light', lightTokens, ':root'))
fs.writeFileSync(path.join(root, 'dist/theme/mathviz-dark.scss'), theme('dark', darkTokens, 'body.quarto-dark'))

const ext = path.join(root, '_extensions/mathviz')
const extDist = path.join(ext, 'dist')
fs.mkdirSync(extDist, { recursive: true })
for (const name of ['mathviz.js', 'mathviz.css']) {
  fs.copyFileSync(path.join(root, 'dist', name), path.join(extDist, name))
}
// The theme, fonts and chrome sit beside dist/ in the extension rather than
// inside it: a site names the theme files by path in its _quarto.yml, and
// the Lua filter adds the fonts and each piece of chrome (sidebar rail,
// embed mode, share, report-bug, mobile warning) as dependencies of their
// own, each only when its option is set -- so none of them belongs in
// the always-loaded bundle. Remove first so a file dropped from src/ doesn't
// linger.
for (const dir of ['theme', 'fonts', 'chrome']) fs.rmSync(path.join(ext, dir), { recursive: true, force: true })
fs.cpSync(path.join(root, 'dist/theme'), path.join(ext, 'theme'), { recursive: true })
for (const dir of ['fonts', 'chrome']) {
  fs.cpSync(path.join(root, 'src', dir), path.join(ext, dir), {
    recursive: true,
    filter: (src) => !src.endsWith('.test.js')
  })
}
for (const name of fs.readdirSync(path.join(ext, 'chrome'))) {
  if (name.endsWith('.js')) execFileSync(process.execPath, ['--check', path.join(ext, 'chrome', name)], { stdio: 'inherit' })
}

// starter/ is a complete Quarto site a newcomer copies and runs; it needs
// the extension installed, which is exactly `_extensions/mathviz/` copied
// in (what `quarto add apurvanakade/mathviz` does). Mirror it here so the
// starter is committed in a working state and tracks the working tree
// rather than a published tag. Remove first so a file deleted from the
// extension doesn't linger in the copy. CI diffs this too.
//
// This script runs in two places. In the mathviz repository starter/ is
// there and gets the mirror. In VisualMathLab -- which authors src/ and
// this script, and mirrors them out (see its CLAUDE.md) -- only the code
// lives under _mathviz/, so there is nothing to mirror into and the step
// is skipped. Guard on the directory rather than on a flag so neither
// checkout has to tell the script which one it is.
if (fs.existsSync(path.join(root, 'starter'))) {
  const starterExt = path.join(root, 'starter/_extensions/mathviz')
  fs.rmSync(starterExt, { recursive: true, force: true })
  fs.cpSync(path.join(root, '_extensions/mathviz'), starterExt, { recursive: true })
}

const kb = (rel) => (fs.statSync(path.join(root, rel)).size / 1024).toFixed(0)
console.log(`dist/mathviz.js  ${kb('dist/mathviz.js')} kB (${js.length} files)`)
console.log(`dist/mathviz.css ${kb('dist/mathviz.css')} kB (${css.length} files)`)
console.log(`dist/theme/mathviz-{light,dark}.scss (${themeTokens.length} tokens each)`)
